#!/bin/bash

docker run -p 8888:8500 -p 8081:8300 -d \
  --name=dev-consul -e CONSUL_BIND_INTERFACE=eth0 consul > /dev/null

container_ip=$(docker inspect dev-consul | \
  jq -r .[0].NetworkSettings.IPAddress)



for x in `seq 1 3`; 
do 
docker run -d -e CONSUL_BIND_INTERFACE=eth0 consul agent \
  -dev -join=$container_ip > /dev/null
done

curl -s  http://127.0.0.1:8888/v1/agent/members | jq -r .[].Name

docker run -v $(pwd):/app -d --name=dev-test\
	-e CONSUL_BIND_INTERFACE=eth0 consul agent -dev -join=$container_ip

